env:
  telegram_bot_token: "5897356168:AAFmBbQ2ZPbKsUuL6xrkIq6GhXPbjHkalTM"
  telegram_id_channel: "1724535418"

task:
  name: "test script"
  timeout_in: 120m
  container:
    image: inok2341/anu:latest
    cpu: 8
    memory: 32G

  Build-Env-Setup_background_script:
    - export DEBIAN_FRONTEND=noninteractive
    - git config --global user.name "indraadp"
    - git config --global user.email "indraproject777@gmail.com"
    - rm -rf ~/ccache
    - mkdir -p ~/ccache
    - curl https://github.com/ccache/ccache/releases/download/v4.8.2/ccache-4.8.2.tar.gz ~/ 
    - mv ~/ccache-4.8.2.tar.gz ccache.tar.gz
    - cd ~/
    - time tar xf ccache.tar.gz
    - cd ~/

  Storage-Checker_background_script:
    - df -h
    - lsblk
    - ls -l -a -h
    - ./sleep.sh

  Sync_script:
    - curl -s https://api.telegram.org/$telegram_bot_token/sendMessage -d chat_id=$telegram_id_channel -d text="Starting Sync RisingTechOSS source...."
    - rm -rf ~/rom
    - mkdir -p ~/rom
    - cd ~/rom
    - rm -rf * .repo
    - repo init -q --no-repo-verify --depth=1 -u repo init -u https://github.com/RisingTechOSS/android -b thirteen --git-lfs -g default,-mips,-darwin,-notdefault
    - git clone https://github.com/zaidanprjkt/local_manifest --depth 1 -b rising .repo/local_manifests
    - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
    - curl -s https://api.telegram.org/$telegram_bot_token/sendMessage -d chat_id=$telegram_id_channel -d text="Sync RisingTechOSS source completed!"

  Build_script:
    - sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
    - curl -s https://api.telegram.org/$telegram_bot_token/sendMessage -d chat_id=$telegram_id_channel -d text="Build NusantaraOS Android 11 started...."
    - ./final.sh
    - curl -s https://api.telegram.org/$telegram_bot_token/sendMessage -d chat_id=$telegram_id_channel -d text="Build completed!"
    - ./collect.sh
    - curl -s https://api.telegram.org/$telegram_bot_token/sendMessage -d chat_id=$telegram_id_channel -d text="Compressing ccache...."

  Upload_script:
    - ./compressing.sh
    - cd ~/
    - curl -s https://api.telegram.org/$telegram_bot_token/sendMessage -d chat_id=$telegram_id_channel -d text="Uploading ccache...."
    - curl -s https://api.telegram.org/$telegram_bot_token/sendMessage -d chat_id=$telegram_id_channel -d text="Ccache NusantaraOS Android 11 uploaded successfully!"
    - curl -s https://api.telegram.org/$telegram_bot_token/sendMessage -d chat_id=$telegram_id_channel -d text="Uploading build...."
    - curl -T ~/rom/out/target/product/juice/risingOS-*.zip 
    - curl -s https://api.telegram.org/$telegram_bot_token/sendMessage -d chat_id=$telegram_id_channel -d text="Build uploaded successfully!"
 